### ISSUE TITLE
Question: why does the bot require write access to code?

### ISSUE THREAD

**Issue by sbromberger** [JuliaComputing/FemtoCleaner.jl#26]
Opening issues/PRs I can understand, but giving write access to a bot seems a bit imprudent.

**Comment by Keno** [comment]
It can't open a PR without pushing to a branch on your repository. That's unfortunately a limitation of the API I'm using. I have however opened an issue with GitHub to try to get some more fine grained permissions options.

**Comment by sbromberger** [comment]
I don't mean to attempt to reengineer this, but why couldn't it fork the repo, make the changes, and then base a PR from the copy?

**Comment by Keno** [comment]
The bot can't have forks.

**Comment by sbromberger** [comment]
Gotcha. Thanks :)
