### ISSUE TITLE
trigger on install not working

### ISSUE THREAD

**Issue by bjarthur** [JuliaComputing/FemtoCleaner.jl#38]
i installed femtocleaner for gadfly four days ago and have yet to receive a PR.

**Comment by Keno** [comment]
Hmm, I don't know. I do generally see it working. You might have gotten unlucky and installed it just as it was updating itself at which point it can sometimes miss a ping. In any case, once it's installed, you can trigger it manually by opening an issue with the title "Run femtocleaner".
