### ISSUE TITLE
FemtoCleaner not running

### ISSUE THREAD

**Issue by mauro3** [JuliaComputing/FemtoCleaner.jl#42]
About 4h ago I pushed a new REQUIRE: https://github.com/mauro3/Parameters.jl/commit/19ea7e532980c118be61d4c5332665fd12d5a4a8
but femtocleaner did not run.  Now about 1h ago I opened a "Run femtocleaner" issue: https://github.com/mauro3/Parameters.jl/issues/39 but no luck either.  Am I too impatient or is something amiss?

It ran before on Parameters.jl https://github.com/mauro3/Parameters.jl/pull/37 but that PR I closed also around 4h ago, in case that is of importance.  Maybe I insulted femtocleaner by just closing its PR ;-)

**Comment by Keno** [comment]
I think you got hit by a combination of anubis being at capacity and the .io DNA outage. I've restarted femtocleaner, just in case. Maybe try again in an hour or so?

**Comment by mauro3** [comment]
It's still not running.  I close and reopened https://github.com/mauro3/Parameters.jl/issues/39, but that did not work.  Opening a new issue https://github.com/mauro3/Parameters.jl/issues/40 didn't work either (open now for 40min).  I'll check back tomorrow.

**Comment by Keno** [comment]
Sorry about that. I'll take a look.

**Comment by mauro3** [comment]
Oh no, it's running my bad.

**Comment by mauro3** [comment]
Now I struggle with the next step.  I did some `bad bot` reviews in the same PR https://github.com/mauro3/Parameters.jl/pull/40, but they don't show up as issues here.

One issue might be that even though, when submitting the review I toggle the radio button "Request changes", that does not show up in the PRs summary (right at the bottom where also the CI results are presented).  So, something might be amiss with my setup, but I cannot figure out what.  Any help appreciated!

**Comment by blegat** [comment]
It is not running for ECOS. 2 days ago, I removed v0.5 dependency in a commit, nothing happened, I opened an [issue](https://github.com/JuliaOpt/ECOS.jl/issues/56), nothing happened, I have opened now [a new issue](https://github.com/JuliaOpt/ECOS.jl/issues/57) but still nothing. However, I have checked, FemToCleaner is activated for all JuliaOpt repos. Any idea of what is wrong ?

**Comment by KristofferC** [comment]
@Keno, is the server still running?

**Comment by Keno** [comment]
Ran out of entropy again :/. I had forgotten to switch over random to urandom in the sandbox. Should be running again.

**Comment by blegat** [comment]
It is indeed, thanks !

**Comment by blegat** [comment]
It seems to have stopped running again: https://github.com/JuliaOpt/SCS.jl/issues/87
