### ISSUE TITLE
Not running on https://github.com/dlfivefifty/HierarchicalMatrices.jl

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaComputing/FemtoCleaner.jl#48]
I have Femtocleaner set up to run on all my repositories, but for some reason it's not running on 

https://github.com/dlfivefifty/HierarchicalMatrices.jl

I can't figure out why.

**Comment by Keno** [comment]
The entropy issue again: https://github.com/JuliaComputing/FemtoCleaner.jl/issues/49. I've restarted it under rr, which should hopefully let us figure out what's happening.

**Comment by rdeits** [comment]
Is FemtoCleaner still down due to the entropy issue? It's activated on https://github.com/rdeits/NNLS.jl and (I think) should have been run when I merged https://github.com/rdeits/NNLS.jl/pull/5 to drop v0.5 support or when I opened https://github.com/rdeits/NNLS.jl/issues/11

**Comment by Keno** [comment]
It's still down (sorry about that, it ran into a bug that hung it afterwards). @KristofferC has PRs open to fix those bugs though, so we'll get it back right after.

**Comment by rdeits** [comment]
Ok, thanks! It's a great bot 😄

**Comment by KristofferC** [comment]
It should be back. Please comment if not.
