### ISSUE TITLE
Automatically change Base.Test to Compat.Test?

### ISSUE THREAD

**Issue by oschulz** [JuliaComputing/FemtoCleaner.jl#50]
Currently, there's a lot of CI testing breakages because `Base.Test` was removed in Julia v0.7. Could FemtoCleaner change `Base.Test` to `Compat.Test` and add `Compat 0.33` to `REQUIRE` for affected packages?

**Comment by oschulz** [comment]
CC @ararslan, @andreasnoack

**Comment by ararslan** [comment]
This would be better than my proposal in #46, which predates `Compat.Test`.

**Comment by Keno** [comment]
I'm gonna close this, since with 0.7, we automatically update `{Base, Compat}.Test` to `Test`. I don't currently plan to support automatic introduction of `Compat` definitions (we already have our hands full with just the 0.7 ones), but that may be a consideration at some point in the future.
