### ISSUE TITLE
Can femotocleaner deal with conflicting exports?

### ISSUE THREAD

**Issue by christopher-dG** [JuliaComputing/FemtoCleaner.jl#63]
I just ran into this issue myself with `Dispatcher`: `DeferredFutures` exports a `reset!` function, and it was being used unqualified. The most recent version of `DataStructures` now also exports `reset!`, and so calls must be qualified.
Would it be somehow possible to check for new exports by dependencies and perform something like https://github.com/invenia/Dispatcher.jl/pull/33 ?

I'll admit I haven't looked much into this repo's code so I don't know how complex it would be, but it's just an idea.

**Comment by KristofferC** [comment]
I think this is a bit out of scope for this package.

**Comment by Keno** [comment]
We have parts of this analysis now, but actually doing anything about this for non-trivial cases (e.g. choosing between Compat and Base) is best left to humans.
