### ISSUE TITLE
HTTP 400 response in server side logs

### ISSUE THREAD

**Issue by Keno** [JuliaComputing/FemtoCleaner.jl#71]
```
[HTTP - 2018-01-09T12:36:09.11 ]: responding with response on connection i=3
HTTP.Response:

HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Length: 17

invalid signature
```
I don't think this was there with the old HttpServer code.
I believe @ararslan saw the same with nanosoldier at some point.

**Comment by KristofferC** [comment]
I'm guessing https://github.com/JuliaWeb/GitHub.jl/commit/42ef052e6f30db7f223a58f74f22e25268273810 is not applied on the current GitHub.jl commit. Perhaps rebasing Github.jl on master would fix it.

**Comment by Keno** [comment]
It's in there. The error message is `invalid signature` rather than `invalid event`.

**Comment by Keno** [comment]
Seems like most requests are failing with this error message now.

**Comment by ararslan** [comment]
Yes, that's the same thing that's been happening with Nanosoldier.

**Comment by KristofferC** [comment]
So are we doing something wrong in GitHub.jl or is HTTP.jl doing something wrong :/ Any ideas @quinnj?

**Comment by Keno** [comment]
I suspect we're not hashing the correct data anymore to compute the digest.

**Comment by ararslan** [comment]
Bump @quinnj. Any ideas?

**Comment by KristofferC** [comment]
This is https://github.com/JuliaWeb/HTTP.jl/issues/140

Most likely fixed by https://github.com/JuliaWeb/HTTP.jl/pull/135.

**Comment by Keno** [comment]
This is fixed. However, after a few days, it stops responding to HTTP requests. No errors in the logs. I've bumped the HTTP.jl dependency and we'll see if that's any better.
