### ISSUE TITLE
`Run femtocleaner` didn't open a PR

### ISSUE THREAD

**Issue by odow** [JuliaComputing/FemtoCleaner.jl#73]
I opened an issue with the title "Run femtocleaner" (https://github.com/odow/SDDP.jl/issues/87) and, although FemtoCleaner ran and created a branch, I had to manually open a PR https://github.com/odow/SDDP.jl/pull/89.

Possibly (un)related: I didn't notice that it had created a branch and so I closed the original issue.

**Comment by Keno** [comment]
This can happen due to femtocleaner outage. Femtocleaner seems to be more or less stable at the moment. Please feel free to file another issue if this happens again in the future.
