### ISSUE TITLE
Femtocleaner down?

### ISSUE THREAD

**Issue by sbromberger** [JuliaComputing/FemtoCleaner.jl#74]
https://github.com/JuliaGraphs/LightGraphs.jl/issues/855

I've never gotten this to work properly. Could someone please verify that I've set everything up correctly? Thank you.

**Comment by mortenpi** [comment]
I have a similar question -- I dropped 0.4/5 from Highlights.jl yesterday (https://github.com/JuliaDocs/Highlights.jl/commit/cf34985c0f26545587850816fb515c90afcd3ea7) which, as far as I can tell, should cause FemtoCleaner to drop by, but I haven't seen any activity.

**Comment by Keno** [comment]
FemtoCleaner is up and running again, but there'll be some additional maintenance over the next week or so to upgrade it to 0.7
