### ISSUE TITLE
Running FemtoCleaner locally detects no deprecations, even though there are plenty

### ISSUE THREAD

**Issue by dpsanders** [JuliaComputing/FemtoCleaner.jl#76]
Running `FemtoCleaner` locally against a local copy of the master branch of https://github.com/JuliaIntervals/IntervalArithmetic.jl/ 
detects no deprecations, even though loading the package on Julia 0.7 gives plenty of deprecation warnings like

```
┌ Warning: Deprecated syntax `parametric method syntax sqrt{T <: AbstractFloat}(a::T, r::RoundingMode)` around /Users/dpsanders/.julia/v0.7/IntervalArithmetic/src/intervals/rounding.jl:235.
│ Use `sqrt(a::T, r::RoundingMode) where T <: AbstractFloat` instead.
```

**Comment by dpsanders** [comment]
Apparently I had to do a `Pkg.update()` on all of the dependencies to get it to work, apologies.

How do you turn the output into a PR?

**Comment by KristofferC** [comment]
You go to the path it prints in the start, commit the files and push to you repo.

**Comment by dpsanders** [comment]
Thanks -- I tried that but I don't see the changes there.

**Comment by dpsanders** [comment]
Ah yes I see, thanks.

**Comment by dpsanders** [comment]
Fantastic! :)
