### ISSUE TITLE
Array{T}(m::Int) where T` is deprecated

### ISSUE THREAD

**Issue by ViralBShah** [JuliaComputing/FemtoCleaner.jl#92]
┌ Warning: `Array{T}(m::Int) where T` is deprecated, use `Array{T}(undef, m)` instead.
│   caller = top-level scope

**Comment by Keno** [comment]
This one is tricky in general, since I need to figure out that the arguments are integers. However, I can certainly do a heuristic one for constants and maybe I'll add full static type inference eventually.
